#ifndef GAME_UI_H
#define GAME_UI_H

// pinned tooltips will allow you to store the ui layout command state for current hovered layout
// currently only goes into depth of 2 (parent + children, no grandchildren and beyond) to keep things
// simple and enforce less complicated ui layouts
// alignments, direction, grid, and scrollbars are maintained
// items are stored as commands, scrollbar will be set as invisible to be regenerated by ui layout instead
// so the layout can handle scroll
// buttons won't work correctly since you don't what the caller wants to handle on click event so ideally
// avoid that, it would still cache the button item so it will visually be there
typedef struct Layout_Cache
{
    CF_Aabb aabb;
    
    UI_Layout_Direction direction;
    UI_Layout_Direction grid_direction;
    UI_Layout_Alignment alignment;
    UI_Layout_Scroll scroll_direction;
    UI_Layout_State state;
    
    // ready only copies
    const char* title;
    fixed UI_Item* items;
    f32 title_font_size;
} Layout_Cache;

typedef struct Game_Log
{
    const char* text;
    fixed Damage_Source* damage_sources;
    
    CF_Arena arena;
    CF_ListNode node;
} Game_Log;

typedef struct Pin_Tooltip
{
    s32 id;
    fixed Layout_Cache* layouts;
    CF_Arena arena;
    b8 do_close;
} Pin_Tooltip;

typedef u8 Game_UI_State;
enum
{
    Game_UI_State_Splash,
    Game_UI_State_Main_Menu,
    Game_UI_State_Options,
    Game_UI_State_Pause,
    Game_UI_State_Play,
};

typedef struct Game_UI
{
    // oldest entry gets drawn on top
    dyna Pin_Tooltip* pin_tooltips;
    dyna Game_Log* logs;
    Node_Pool log_pool;
    
    CF_ButtonBinding do_close_window;
    
    b32 show_inventory;
    
    CF_Coroutine state_co;
    dyna Game_UI_State* states;
} Game_UI;

void init_game_ui();
void update_game_ui();

void game_ui_push_state(Game_UI_State state);
Game_UI_State game_ui_peek_state();
Game_UI_State game_ui_pop_state();
void game_ui_set_state(Game_UI_State state);

void game_ui_tooltip_begin();
void game_ui_tooltip_end();
void game_ui_tooltip(const char* fmt, ...);
void game_ui_close_all_tooltips();

void game_ui_do_tooltip_content(Pin_Tooltip* pin_tooltip);
void game_ui_do_tooltips();
b32 game_ui_pin_tooltip_just_pressed();

void game_ui_creature_tooltip(Body_Type body_type);
void game_ui_spell_tooltip(Spell_Type spell_type);
void game_ui_item_tooltip(Item_Type item_type);

b32 game_ui_do_button(const char* fmt, ...);
b32 game_ui_do_slider(f32 *value, f32 min, f32 max, f32 rate);

void game_ui_clear_logs();
void game_ui_do_logs();
void game_ui_do_creature_hud();
void game_ui_do_spell_hud();
void game_ui_do_arena_placement();
void game_ui_do_arena_in_progress();
void game_ui_do_arena_result();
void game_ui_do_shop();
void game_ui_do_inventory();

void game_ui_log_damage(const char* attacker, const char* victim, fixed Damage_Source* sources);
void game_ui_log_died(const char* victim);

void game_ui_log_condition_gained(const char* victim, Condition_Effect_Type effect);
void game_ui_log_condition_loss(const char* victim, Condition_Effect_Type effect);
void game_ui_log_condition_expired(const char* victim, Condition_Effect_Type effect);
void game_ui_log_condition_tick(const char* victim, Condition_Effect_Type effect, s32 damage);

void game_ui_log_condition_inflict(const char* attacker, const char* victim, Condition_Effect_Type effect);
void game_ui_log_condition_purge(const char* attacker, const char* victim, Condition_Effect_Type effect);

void game_ui_log_hand_select_spell(Spell_Type spell);
void game_ui_log_hand_cast_spell(Spell_Type spell);
void game_ui_log_hand_condition_add(const char* victim, Condition_Effect_Type effect);
void game_ui_log_hand_condition_remove(const char* victim, Condition_Effect_Type effect);
void game_ui_log_hand_damage(const char* victim, Spell_Type spell, s32 damage);

void game_ui_log_hand_slap(const char* victim);

// misc
fixed char* game_ui_attributes_health_tooltip(CF_MAP(Attributes) attributes);
fixed char* game_ui_attributes_strength_tooltip(CF_MAP(Attributes) attributes);
fixed char* game_ui_attributes_agility_tooltip(CF_MAP(Attributes) attributes);
fixed char* game_ui_attributes_move_speed_tooltip(CF_MAP(Attributes) attributes);

// ui states
void game_ui_do_splash_co(CF_Coroutine co);
void game_ui_do_splash();
void game_ui_do_main_menu();
void game_ui_do_options();
void game_ui_do_pause();
void game_ui_do_play();
void game_ui_do_debug_stats();

void profiler_ui_do_flame_graph(Profiler* profiler, s32 frame_index);

#endif //GAME_UI_H
